In [ ]:
import numpy as np

# 1D array from a list
a = np.array([1, 2, 3, 4])
print(a)         # [1 2 3 4]

# 2D array from nested lists
b = np.array([[1,2,3],[4,5,6]])
print(b)
# [[1 2 3]
#  [4 5 6]]

# Using built-in array creators
zero = np.zeros((2,3))       # 2x3 of zeros
one = np.ones((3,3))         # 3x3 of ones
ar = np.arange(0,10,2)        # like range() → [0 2 4 6 8]
lin = np.linspace(0,1,5)      # 5 numbers from 0 to 1

print(zeros)
print(ones)
print(ar)
print(lin)

arr = np.array([[1,2,3,4],[2 , 4,4,5,]])
print(arr)

zeros = np.zeros((2,3))
ones = np.ones((3,3))
ar = np.arange(3 , 21 , 3)
lin = np.linspace(0 , 10 , 10) # start from zero and stop at 1 and between these two numbers there should be 5 numbers

print(zeros)
print(ones)
print(ar)
print(lin)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[1 2 3 4]
 [2 4 4 5]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 3  6  9 12 15 18]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)   # (2, 3) rows x columns
print(arr.ndim)    # 2 dimensions
print(arr.size)    # 6 elements total
print(arr.dtype)   # int64 (or platform dependent)


shap = arr.shape
print(shap)  # to find the size if the array .shape is used 

N_Dim = arr.ndim
print(N_Dim)  # to the N number of dimensions in an array

size = arr.size
print(size) # finds how many elements are there in an array or multi dimensional array

which_type = arr.dtype
print(which_type) 



(2, 3)
2
6
int64
(2, 3)


In [12]:
a = np.array([10,20,30,40,50])
print(a[0])        # first element 10
print(a[1:4])      # slice from index 1 up to 4 (exclusive) → [20 30 40]

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[1,2])      # element at row1,col2 = 6
print(b[:2,1:])    # first 2 rows, columns from index 1 onward
print(b[2,0])

10
[20 30 40]
6
[[2 3]
 [5 6]]
7


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)   # [5 7 9]
print(a * b)   # [ 4 10 18]
print(a ** 2)  # [1 4 9] ** means power

# Matrix multiplication
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
print(m1 @ m2)

[5 7 9]
[ 4 10 18]
[1 4 9]
[[19 22]
 [43 50]]
